### PR TITLE
FIX: Fixes #15 Non ADMIN users unable to use "Files" admin

### LINKED ISSUE #15: Bug with standard assets permissions
v1.0.3 / PHP 5.5.9

At present if a user is created who has / inherits CMS permissions to see the "Files" (CMS standard asset-admin) and this module is installed, the CMS simply redirects to /admin/pages for some reason and the "Files" LHS menu item does not appear. 

Adding a canView() that returns true to `NonSecuredAssetAdmin` allows the menu to show again, but clicking it or pasting /admin/assets into the address bar, performs a redirect as stated above.

Removing the advanced assets module, makes the issue disappear.

### PR DESCRIPTION
**Pull request by phptek**
- Tightened security on root assets folder.
- Completely refactored unit-tests for consistency and to increase coverage.
- Boyscouting phpdoc and newlines.

### CODE REVIEW

File: code/extensions/FileSecured.php [hunk 1]
```diff
@@ -397,7 +406,21 @@ public static function find_or_make_secured($folderPath) {
...
+    }
+
+    /**
+     * Check if the initial permission settings for the root "secured" (advanced) folder
+     * are those found in the legacy (initial) version of this module.
+     *
+     * @param Folder $rootFolder
+     * @return boolean
+     */
+    public static function root_folder_has_legacy_settings(Folder $rootFolder) {
```
Comment (normann) [inline code/extensions/FileSecured.php]: Is this function still necessary? where is it called?

**Comment by normann** [comment]
@phptek as a whole, we need to default the 'SecurityRoot' folder's CanViewType as "Anyone" and CanEditType as "LoggedInUsers" in the FileSecured::find_or_make_secured() function when create that folder. Other than that, everything is good to go, thou I didn't check out the test case cos I trust you (have run the test successfully). :)

**Comment by normann** [comment]
Look good.
